name: CI
on:
  push:
    branches:
      - master
env:
  RELEASE_ID: 1.0.1
jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: Install dependencies
        run: npm install
      - name: Build on MacOS
        env:
          ELECTRON: true
          APP_VERSION_NUMBER: 0.5.9
        run: npm run dist
      # - name: Build Electron
      #   env:
      #     ELECTRON: true
      #     APP_VERSION_NUMBER: 0.5.9
      #   run: npm electron:buildUnix
      - name: see directory
        run: ls
      - name: check env
        run: echo $ELECTRON $FEATHERS_URL
      - name: see directory in dist
        run: ls ./dist
      - uses: lucyio/upload-to-release@master
        with:
          # repo username/name
          name: janmei/unimore
          # directory of all your files you want to upload (not recursive only flat, directories are skipped)
          path: ./dist
          # can be enum of published, unpublished, created, prereleased
          action: unpublished
          # release tag
          release_id: $RELEASE_ID
          # release repository name
          release-repo: janmei/unimore
          # secret for your github token to use
          repo-token: ${{ secrets.github_token_release }}
